//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carpooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATAHORA { get; set; }
        public int CARRO_CARROID { get; set; }
        public int DESTINOFINAL_DESTINOID { get; set; }
        public int USUARIOPROPRIETARIO_ID { get; set; }
    
        public virtual DESTINO DESTINO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual VEICULO VEICULO { get; set; }
    }
}
