//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carpooling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carpoolingEntities : DbContext
    {
        public carpoolingEntities()
            : base("name=carpoolingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGENDA> AGENDA { get; set; }
        public DbSet<AGENDA_USUARIOS> AGENDA_USUARIOS { get; set; }
        public DbSet<DESTINO> DESTINO { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VEICULO> VEICULO { get; set; }
    }
}
