//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carpooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO
    {
        public VEICULO()
        {
            this.AGENDA = new HashSet<AGENDA>();
        }
    
        public int ID { get; set; }
        public string MODELO { get; set; }
        public string PLACA { get; set; }
        public string COR { get; set; }
        public int CAPACIDADE { get; set; }
        public int USUARIO_ID { get; set; }
    
        public virtual ICollection<AGENDA> AGENDA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
